services:
  ### ===================================
  ### API SERVICE TERITORY
  ### ===================================
  api:
    container_name: go-api
    restart: always
    build:
      context: .
      dockerfile: external/deployments/Dockerfile
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    depends_on:
      - db
      - cache
    ports:
      - 3000:3000
    networks:
       - go-network
  ### ===================================
  ### DATABASE SERVICE TERITORY
  ### ===================================
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
       - go-network
  ### ===================================
  ### CACHING SERVICE TERITORY
  ### ===================================
  cache:
    image: redis:7-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
       - go-network
  ### ===================================
  ### NETWORKS SHARING GROUP TERITORY
  ### ===================================
networks:
  go-network: